### ISSUE TITLE
Missing pygame

### ISSUE THREAD

**Issue by SilversApprentice** [Sigton/stealth#1]
Unless my computer is acting up, the repo is missing the required `pygame` module. If you could add that in, that would be helpful :P

**Comment by Sigton** [comment]
Sure, but I really recommend you download it (http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame) since it's a very useful and commonly used module.

Sigton

**Comment by SilversApprentice** [comment]
Indeed.
