### ISSUE TITLE
Is the game containing a malware?

### ISSUE THREAD

**Issue by fowled** [Sigton/stealth#6]
Hello,
I know this game/repository is quite old, but I discovered it today and liked the design of your game.
So I wanted to download it... Once finished, I scanned the folder `Stealth-1.0.2.win-amd64.zip` with VirusTotal and one engine detected the game as a virus...

![image](https://user-images.githubusercontent.com/37367577/56471742-1c85b300-6456-11e9-897b-146f239e85f9.png)

Although I think it's a false positive, I'd like to be sure that the game is 100% clean.

Thanks!

**Comment by SilversApprentice** [comment]
This is 100% a false positive, the game is clean.

**Comment by fowled** [comment]
> This is 100% a false positive, the game is clean.

Ok, thank you ;)

**Comment by SilversApprentice** [comment]
No problem

**Comment by Treehee** [comment]
I'd say it's still worth looking into why it gives that warning, even though the game is safe, to avoid user confusion in the future.

**Comment by fowled** [comment]
Reopening because Sigton didn't answer that question...

**Comment by fowled** [comment]
Changed the title and still leaving this issue opened for Sigton & I, waiting for my answer 😄

**Comment by fowled** [comment]
Is @Sigton dead?
